/* ------------------------------------------------------------------------
   html-de.js — die Rahmentexte der Abschnitte auf Deutsch.

   Sie stehen hier und nicht im HTML, damit der Sprachschalter sie
   zurückholen kann, wenn von einer anderen Sprache umgestellt wird.
   ------------------------------------------------------------------------ */

export const HTML_DE = {
  "bHoroskop.titel": "Das Horoskop",
  "bHoroskop.unter": "Die Radix, ihre Transite und ihre Progression",
  "bHoroskop.ein1": "Die Zeitherrscher-Techniken dieser Seite — Profektionen, Zodiacal Releasing, der Lebensbogen — sagen, wann etwas fällig wird. Was fällig wird, steht hier. Ohne die Deutung des Geburtshoroskops bleiben jene Techniken ein Kalender ohne Inhalt; mit ihr werden sie konkret.",
  "bHoroskop.ein2": "Im Horoskop stehen die Planeten da, aber sie beantworten keine Frage. Klick ein Feld an — Geld, Arbeit, Ehe, Kinder, Ruf —, und es wird nach dem klassischen Verfahren durchgerechnet: der Herr des Feldes und sein Stand, wer im Feld steht, wer den Herrn ansieht, und der alte Anzeiger der Sache. Beim fünften Feld kommt die hellenistische Frage nach der Kinderzahl dazu, beim zehnten der Rang des Ruhms nach Ptolemäus.",
  "bYildiz.titel": "Yıldıznâme",
  "bYildiz.unter": "Das Sternbuch — ein Horoskop ohne Geburtsdatum",
  "bYildiz.ein1": "Der eigene Name und der Name der Mutter — so fragen die Handschriften, denn die Mutter ist zweifelsfrei. Beide werden arabisch geschrieben, ihre Buchstaben im Ebced addiert, die Summe geteilt.",
  "bNiyet.ein1": "Die niyet cetveli, die Tafel der Absicht: nicht das Wesen, sondern die eine Frage. Gerechnet wird aus den Buchstaben der Frage, dem Namen des Fragenden und der Stunde, in der gefragt wird.",
  "bUyum.ein1": "Zwei Menschen, vier Namen. Die Handschriften rechnen beide Summen gegeneinander und lesen dazu die alte Regel der Elemente.",
  "bMenzil.titel": "Der rechte Zeitpunkt",
  "bMenzil.unter": "Elektion nach den achtundzwanzig Mondstationen",
  "bMenzil.ein1": "Die Wahlastrologie fragt nicht, wer du bist, sondern wann etwas beginnen soll. Ihr ältestes Werkzeug sind die menâzil-i kamer, die achtundzwanzig Herbergen des Mondes: Er zieht in gut siebenundzwanzig Tagen hindurch und wechselt fast täglich die Station — und jede hat, wofür sie taugt und wovor sie warnt.",
  "bRamel.titel": "ʿIlm al-Raml",
  "bRamel.unter": "Die Sandkunst — Punkte, Figuren, ein Richter",
  "bRamel.ein1": "Man zieht mit dem Finger Reihen von Punkten in den Sand, ohne sie zu zählen, und liest nur, ob ihre Zahl gerade oder ungerade war. Vier Reihen ergeben eine Figur, vier Figuren die Mütter. Aus ihnen wächst nach festen Regeln ein ganzer Schild: Töchter, Nichten, zwei Zeugen — und zuletzt der Richter, der antwortet. Über Nordafrika kam das Verfahren als geomantia nach Europa; die sechzehn Figuren tragen dort lateinische Namen.",
  "bProfil.titel": "Das Leuchten",
  "bProfil.unter": "Ein Leben, vor- und zurückgespult",
  "bProfil.ein1": "Vier Zeitherrscher-Systeme laufen nebeneinander her — Zodiacal Releasing, die Profektion, die persische Firdaria und die indische Vimshottari. Jedes nennt zu jedem Alter einen Herrn. Hier liegen sie übereinander: Zieh die Leiste durch dein Leben und sieh, worauf sie gemeinsam zeigen. Wo viele dasselbe sagen, brennt es hell und einfarbig; wo jedes etwas anderes sagt, bleibt es matt und vielfarbig.",
  "bGeist.titel": "Spirit Name",
  "bGeist.unter": "Der Geist des 11. Hauses — nach Agrippa",
  "bGeist.ein1": "Ein anderes Buch als das Yıldıznâme: Cornelius Agrippas De Occulta Philosophia (Buch III, Kap. 26). Statt des Namens fragt dieses Verfahren den wirklichen Himmel zur Geburtsstunde. Aus Geburtsdatum, -zeit und -ort werden die fünf hylegischen Örter berechnet — Aszendent, Sonne, Mond, Glückspunkt und die Syzygie vor der Geburt. Über den Tierkreis liegt der Kreis der hebräischen Buchstaben; jeder Ort fällt in einen Sektor und gibt seinen Buchstaben her. Die fünf zusammen ergeben den Geistnamen. Dazu, als eigene Aussage, der Almuten des 11. Hauses — der Regent des Hauses des „guten Geistes\".",
  "bLebensbogen.ein1": "Die älteste Vorhersagetechnik der westlichen Astrologie, systematisiert von Ptolemäus (Tetrabiblos III), in der Neuzeit wiederentdeckt u. a. durch Martin Gansten (Primary Directions, 2009). Nicht die Planeten bewegen sich — der ganze Himmel dreht sich um die Weltachse, rund einen Grad pro vier Zeitminuten, im Schlüssel des Ptolemäus also ein Grad pro Lebensjahr. Ein Promissor \"kommt zur Richtung\", wenn diese Drehung ihn auf die Stelle eines Signifikators bringt.",
  "bZR.ein1": "Eine hellenistische Zeitherren-Technik, überliefert bei Vettius Valens und in der Neuzeit vor allem durch Robert Hand wieder zugänglich gemacht. Von einem Los — dem Los des Glücks (Körper, Umstände) oder dem Los des Geistes (Handeln, Absicht) — werden die zwölf Zeichen \"freigesetzt\", jedes so viele Jahre lang, wie sein Herrscher an \"kleineren Jahren\" trägt; jede Stufe verschachtelt dieselbe Zählung fein in sich selbst.",
  "bAntiszien.ein1": "Ein griechisches System aus der hellenistischen Astrologie: Antiszien (griech. anti gegenüber + skia Schatten) sind zwei Punkte der Ekliptik mit derselben Sonnendeklination, gespiegelt an der Sonnwendachse (0° Krebs/0° Steinbock) — an ihnen wirft die Sonne am selben Ort den gleich langen Mittagsschatten, und für jeden Tag im Jahr außer den vier Kardinalpunkten gibt es so einen kalendarischen Schattenzwilling. Die Kontra-Antiszien spiegeln stattdessen an der Äquinoktialachse (0° Widder/0° Waage) — entgegengesetzte Deklination, Tag und Nacht vertauscht.",
  "bProfektionen.ein1": "Eine hellenistische Zeitherren-Technik neben Zodiacal Releasing, überliefert u. a. bei Vettius Valens: Nicht die Planeten wandern, sondern die Häuser. Mit jedem Lebensjahr rückt die Zählung, in Ganzzeichen-Häusern, um ein Zeichen weiter — im Geburtsjahr steht das Zeichen des Aszendenten selbst auf dem I. Haus, ein Jahr später das nächste, und so fort. Der Herrscher des profizierten I. Hauses ist der Herr des Jahres. Die zwölf Monate eines Jahres profizieren auf dieselbe Weise weiter, beim Zeichen des Jahres beginnend.",
  "bFirdaria.titel": "Firdaria",
  "bFirdaria.unter": "Fünfundsiebzig Jahre auf neun Herren",
  "bFirdaria.ein1": "Aus dem persisch-arabischen Zweig, bei Abū Maʿšar und den Seinen. Das Leben wird nicht in Zeichen abgezählt, sondern in feste Jahresmengen zerlegt: Sonne zehn, Venus acht, Merkur dreizehn, Mond neun, Saturn elf, Jupiter zwölf, Mars sieben — dazu die beiden Mondknoten mit drei und zwei. Zusammen fünfundsiebzig. Die Reihenfolge hängt an einer einzigen Frage: Stand die Sonne bei der Geburt über oder unter dem Horizont?",
  "bVimshottari.titel": "Vimshottari Dasha",
  "bVimshottari.unter": "Hundertzwanzig Jahre, gezählt vom Mondhaus der Geburt",
  "bVimshottari.ein1": "Das verbreitetste Zeitsystem der indischen Astrologie. Hundertzwanzig Jahre verteilen sich auf neun Herren — Ketu sieben, Venus zwanzig, Sonne sechs, Mond zehn, Mars sieben, Rahu achtzehn, Jupiter sechzehn, Saturn neunzehn, Merkur siebzehn. Welcher beginnt, entscheidet der Mond: In welchem seiner siebenundzwanzig Häuser er bei der Geburt stand, und wie weit er darin schon gekommen war. Gerechnet wird siderisch, nicht tropisch — der Unterschied beträgt derzeit gut vierundzwanzig Grad.",
  "bNasil.titel": "Die Idee dahinter",
  "bNasil.unter": "Woher die Verfahren kommen und was sie behaupten",
  "bNasil.ein1": "Oracle versammelt Techniken, die über zweitausend Jahre und drei Kulturkreise verteilt entstanden sind — hellenistisch, arabisch-osmanisch, ägyptisch, lateinisch-europäisch. Sie widersprechen einander in vielem. Was sie teilen, ist eine Annahme: Ein Zeitpunkt oder ein Name ist kein leerer Behälter, sondern hat eine Gestalt, und diese Gestalt lässt sich abzählen.",
  "bNasil.ein2": "Die rechnende Astrologie sagt, wo ein Planet steht. Was er ist, sagt sie nicht — das steht in anderen Büchern. Im Picatrix, dem arabischen Ġāyat al-Ḥakīm aus dem zehnten Jahrhundert, das im dreizehnten ins Lateinische kam, und bei Agrippa in der Occulta Philosophia. Diese Bücher geben jedem Planeten eine Gestalt, ein Metall, einen Tag, eine Farbe und eine lange Liste dessen, was er bedeutet.",
  "bSolar.titel": "Die Jahresumdrehung",
  "bSolar.unter": "Solar Revolution nach Abū Maʿšar",
  "bSolar.ein1": "Einmal im Jahr kehrt die Sonne genau auf den Grad zurück, auf dem sie bei deiner Geburt stand. Für diesen Augenblick wird ein Horoskop gestellt — das Horoskop des Jahres. Abū Maʿšar hat das Verfahren in „Über die Umdrehungen der Jahre der Geburten“ ausgearbeitet, und er verlangt eine feste Reihenfolge der Befragung. Dieser Abschnitt geht sie Schritt für Schritt durch — und kommt erst am Ende zur Deutung.",
  "bRadixdeutung.titel": "Die Deutung",
  "bRadixdeutung.unter": "Die Geburt als Ganzes — durch zwei Brillen gelesen",
  "bRadixdeutung.ein1": "Alle anderen Abschnitte sagen, wann etwas fällig wird. Dieser sagt, was fällig wird. In der alten Schule steht er vor allen übrigen, und Robert Zoller fasst die Regel in vier Worte: keine Deutung, keine Vorhersage. Wer das Geburtsbild nicht zuerst als Ganzes gelesen hat, bekommt aus den Zeitherren nur einen Kalender ohne Inhalt.",
  "bAlmutem.titel": "Der Herr der Geburt",
  "bAlmutem.unter": "Almutem Figuris — wer über das Ganze zu sagen hat",
  "bAlmutem.ein1": "Alles andere auf dieser Seite fragt nach einzelnen Dingen: wer dieses Jahr regiert, wer dieses Feld, wer diese Stunde. Der Almutem Figuris fragt nach dem Ganzen — welcher der sieben über diese Geburt als solche am meisten zu sagen hat. Bei Abraham Ibn Ezra (Sefer ha-Moladot, 12. Jh.) steht das Verfahren zuerst geschlossen beisammen, Guido Bonatti nimmt es in den Liber Astronomiae auf. In der mittelalterlichen Schule gilt er als der Schlüssel zur ganzen Deutung: Wer ihn nicht kennt, deutet Einzelheiten ohne Mitte.",
  "bWerk.titel": "Das Werk",
  "bWerk.unter": "Der Herr des Werks nach Ptolemäus — woraus deine Arbeit gemacht ist",
  "bWerk.ein1": "Ptolemäus (Tetrabiblos IV.4) fragt nicht, welchen Beruf jemand ergreift, sondern aus welchem Stoff seine Tätigkeit ist. Er sucht dafür zwei Stellen ab — den Planeten, der morgens vor der Sonne aufgeht, und den am Himmelsmittelpunkt — und lässt nur drei als Herrn des Werks gelten: Merkur, Venus und Mars. Alles Hervorbringen, sagt er, geht durch Hand, Auge oder Wort. Die übrigen vier geben Rang und Umstände, nicht das Werk selbst.",
  "bLebensalter.titel": "Die drei Lebensalter",
  "bLebensalter.unter": "Die Triplizitätsherren nach Dorotheos",
  "bLebensalter.ein1": "Jedes Element hat drei Herren: einen für den Tag, einen für die Nacht und einen dritten, den die arabische Überlieferung den Teilhaber nennt. Dorotheos teilt das Leben in drei Teile und gibt jedem einen von ihnen. Wie dieser Herr steht, so verläuft sein Drittel. Es ist die einfachste Zeitteilung der ganzen Überlieferung — und zugleich die gröbste: Sie sagt eine Tendenz, keinen Termin.",
  "bPunkte.titel": "Die arabischen Punkte",
  "bPunkte.unter": "Partes — gerechnete Stellen, keine Himmelskörper",
  "bPunkte.ein1": "Sie heißen arabisch, sind aber älter: Schon Paulus Alexandrinus und der Liber Hermetis kennen sie. Ein Punkt entsteht immer gleich — man nimmt den Abstand zwischen zwei Stellen des Horoskops und trägt ihn vom Aufsteigenden aus noch einmal ab. Was herauskommt, ist kein Himmelskörper, sondern ein Ort, an dem zwei Bedeutungen sich treffen. Guido Bonatti führt siebenundneunzig davon auf; hier stehen die sieben hermetischen und die gebräuchlichsten.",
  "bVerteilung.titel": "Die Verteilung",
  "bVerteilung.unter": "Durch die Grenzen — qisma, jārbakhtār, distributio per fines",
  "bVerteilung.ein1": "Die eigentliche Zeitherren-Technik des Dorotheos von Sidon (Carmen Astrologicum, 1. Jahrhundert), über das Pahlavi ins Arabische gekommen und bei ʿUmar al-Tabarī und Abū Maʿšar ausgebaut. Sie arbeitet anders als alles andere auf dieser Seite: Nicht ein Zeichen pro Jahr wie die Profektion, nicht feste Mengen wie die Firdaria — sondern der Aszendent wandert mit der Drehung des Himmels durch die fünf Grenzen jedes Zeichens, und jede Grenze dauert so lange, wie sie an deinem Geburtsort wirklich zum Aufgehen braucht.",
  "bLebensmass.titel": "Das Lebensmaß",
  "bLebensmass.unter": "Hylech und Alkochoden — die umstrittenste Technik der Überlieferung",
  "bLebensmass.ein1": "Zuerst wird der Hylech gesucht (arabisch haylāj, griechisch aphetes, „der Loslassende“): jene Stelle des Horoskops, von der das Leben ausgeht. Dann der Alkochoden (kadkhudāh, „der Hausherr“): der Planet, der über dieser Stelle die meiste Würde hat. Er gibt seine Jahre her — seine größten, mittleren oder kleinsten, je nachdem, wie er selbst steht.",
  "bEssenz.ein1": "Alles, was die einzelnen Abschnitte gefunden haben, in einem Stück gelesen — das Wesen aus dem Namen, der Geist aus dem Himmel der Geburtsstunde, und wo du gerade in der Zeit stehst.",

  /* Was jedes Technikfeld der Wegeliste verspricht. */
  "worum.bHoroskop": "Der Himmel deiner Geburtsstunde: Aszendent, die sieben Planeten in Zeichen und Feldern, ihre Würden und Winkel. Dazu die zwölf Felder des Lebens, einzeln befragt.",
  "worum.bYildiz": "Das osmanische Sternbuch. Dein Name und der deiner Mutter werden zu Zahlen, die Summe fällt in ein Fach des Himmels.",
  "worum.bNiyet": "Die Tafel der Absicht. Nicht die Sache wird gefragt, sondern der Augenblick, in dem du fragst.",
  "worum.bUyum": "Zwei Menschen, vier Namen. Die Handschriften rechnen beide Summen gegeneinander und lesen die alte Regel der Elemente.",
  "worum.bMenzil": "Die Wahlastrologie. Wann fängt man etwas an? Der Mond zieht durch achtundzwanzig Herbergen, und jede hat ihr Urteil.",
  "worum.bRamel": "Die Sandkunst. Sechzehn Figuren aus geraden und ungeraden Punkten, aus vier Müttern wächst ein ganzes Feld.",
  "worum.bGeist": "Agrippas Geist des elften Hauses — ein Name, der nicht aus deinem Namen kommt, sondern aus fünf Orten deines Himmels.",
  "worum.bLebensbogen": "Die älteste Vorhersagetechnik des Westens: ein Grad der Himmelsdrehung für ein Lebensjahr.",
  "worum.bZR": "Die Kapitel deines Lebens, nach Vettius Valens — mit ihren Unterkapiteln, den Höhepunkten und der Stelle, an der ein Faden reißt.",
  "worum.bAntiszien": "Die Schattenzwillinge: Punkte, die einander nicht ansehen und doch denselben Schatten werfen.",
  "worum.bProfektionen": "Ein Zeiger, der jedes Jahr ein Feld weiterrückt. Worum es von Geburtstag zu Geburtstag geht — und wer das Jahr führt.",
  "worum.bFirdaria": "Die persische Zählung des Abū Maʿšar: feste Mengen von Jahren, jede unter einer anderen Hand.",
  "worum.bVimshottari": "Das verbreitetste Zeitsystem Indiens, gerechnet vom Stand des Mondes bei deiner Geburt.",
  "worum.bSolar": "Einmal im Jahr kehrt die Sonne auf ihren Geburtsgrad zurück. Was dieses Jahr trägt — in neun Schritten nach Abū Maʿšar.",
  "worum.bRadixdeutung": "Die Geburt als Ganzes, ehe die Zeit anfängt — Sekte, Temperament, der Aufsteigende und sein Herr. Wahlweise nüchtern nach Bonatti oder in Bildern und Fabeln.",
  "worum.bAlmutem": "Der Herr des ganzen Horoskops nach Ibn Ezra und Bonatti — wer über diese Geburt als solche das letzte Wort hat, wenn die einzelnen Zeugen sich widersprechen.",
  "worum.bWerk": "Ptolemäus fragt nicht nach dem Beruf, sondern aus welchem Stoff deine Arbeit ist — durch Hand, Auge oder Wort.",
  "worum.bLebensalter": "Dorotheos teilt das Leben in drei Teile und gibt jedem einen der drei Herren deines Elements.",
  "worum.bPunkte": "Gerechnete Stellen, keine Himmelskörper: wo Glück, Geist, Liebe, Vater, Mutter und die übrigen im Horoskop zu liegen kommen.",
  "worum.bVerteilung": "Dorotheos' Verteilung durch die Grenzen: Der Aszendent wandert mit der Drehung des Himmels, und jede Grenze dauert so lange, wie sie an deinem Ort zum Aufgehen braucht.",
  "worum.bLebensmass": "Die alte Frage nach dem Maß des Lebens: Hylech und Alcocoden, der Geber und der Hüter.",
  "worum.bEssenz": "Alles zusammen, in Bildern statt in Fachsprache — was die einzelnen Künste gemeinsam sagen."
};
